[package]
name = "cargo-release-commit"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.42"
cargo_metadata = "0.14.0"
cradle = "0.0.18"
question = "0.2.2"
structopt = "0.3.22"
tempfile = "3.2.0"
